FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# btc-app-server

Manage your account and interact with the Bicycle Touring Companion.

## Account Management [/register]

### Initiate Account Creation [POST]

You may create your own account at this endpoint. It takes a JSON
object containing all your standard account details. Once you request an 
account, we'll send you an email containing a verification token.

+ Request (application/json)
    
        {
            "email": "john.doe@example.com",
            "password": "123456",
            "first": "john",
            "last": "doe",
            "username": "johndoe"
        }

+ Response 200 (application/json)
+ Response 400 (application/json)

        {
            "error": "something went wrong"
        }
        
## Account Management: Verification [/register/{token}]

Respond here with the token we send to your email address.

+ Parameters
    + token (string) - The JWT we sent to your email address
    
### Verify Email [GET]

+ Response 200 (text/html)
+ Response 400 (text/html)